all:
	cp ./node_modules/cra-template/template/public/logo512.png public
	cp ./node_modules/cra-template/template/public/logo192.png public
	cp ./node_modules/cra-template/template/public/favicon.ico public
	yarn build && surge build abrasive-aunt.surge.sh
